### ISSUE TITLE
Backfilling Sales and Asks for Contracts

### ISSUE THREAD

**Issue by felixjchen** [reservoirprotocol/reservoir-light-indexer#15]
Hi ! 

Our use case involves backfilling / subscribing to resevoir's sales and listing tables. We're only concerned about a few NFT collections.

Playing around with this node I found that:
- Asks were not populating into the DB
- Sales only populated ~10
- Ask requests were not being filted by collection
- Ask requests cannot have any status

I tried modifying the code to our use case, but I bumped into some API walls:
```
% curl --request GET \
    --url 'https://api.reservoir.tools/orders/asks/v4?sortDirection=asc&limit=12&includeCriteriaMetadata=true&sortBy=updatedAt&startTimestamp=1682899200&endTimestamp=1685577599&contracts=0x76be3b62873462d2142405439777e971754e8e77' \              
    --header 'accept: */*' \                                  
    --header 'x-api-key: X'
{"statusCode":400,"error":"Bad Request","message":"Cannot filter by contracts while sortBy = \"updatedAt\" and status = \"any\""}%     
```

**Comment by r3lays** [comment]
Hey @felixjchen! Glad to see you trying things out - apologies for the issues. Hopefully we can get those sorted out for you.

For starters, would you mind sharing your configuration with me so I can attempt to replicate?
Chain, Contract(s), worker count, manager count

Regarding "Ask requests were not being filted by collection" the reason you don't see them being passed into the request is due to some limitations on that API currently. We're hoping to fix that issue soon. Currently the node should filter out the contracts you passed in on the client itself.

"Ask requests cannot have any status" could you elaborate on this? FWIW currently we backfill the data by only fetching the active asks and then once we reach the upkeep stage (present) we switch to an "any" status filter as opposed to just "active" in order to catch those asks that have been updated.

"Asks were not populating into the DB" - I'll take a look at this. We recently made some changes to the prisma aspect of the LightNode and this might've caused somethings to change that we were unaware of.

Also just a heads up, seems like you might've included your API key in the request!

**Comment by felixjchen** [comment]
Chain - Mainnet
Contract - 0x76be3b62873462d2142405439777e971754e8e77
Worker / Manager counts - Default 

Ask requests were not being filted by collection - Yeah I figured out this limitation playing around with the API and your query params. 

Ask requests cannot have any status - We're trying to build a historical floor for some contracts. To do that we need to see how listings got filled or cancelled in the past to figure how which listings are valid at any point in time. Sounds like your backfill + upkeep does manage to close out historical listings ?

Let me know, this project seems well written and we'd be happy to add it to our stack.

**Comment by felixjchen** [comment]
Hey @r3lays,

` Currently the node should filter out the contracts you passed in on the client itself.` Is this why the insertion counts for managers are blowing up while the DB count is low ? I had a look through and looks like you might want to insertCount = sum(upsertCount) - sum(deleteCount), I see deletion is part of the contract filtering, **I wish the API just did contract filtering.**
